### ISSUE TITLE
Make OpenTable url protocol agnostic

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Open-Table-Widget#4]
Refer to this Pro commit:

https://github.com/WordImpress/Open-Table-Widget-Pro/commit/7d44ad6203e2386e4d389974241b40a18242d3d6

**Comment by lchski** [comment]
Not sure this one is actually an issue. Because the free widget only supports US/Canada-based restaurants, it only queries one URL, which is already hard-coded into the widget without a protocol: https://github.com/WordImpress/Open-Table-Widget/blob/master/inc/widget-frontend.php#L20

**Comment by mathetos** [comment]
You're right. Closed.
